"""add_display_order_to_question_options

Revision ID: 1db4d2c894c6
Revises: db865e840e17
Create Date: 2026-06-04 11:52:04.583024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1db4d2c894c6'
down_revision: Union[str, None] = 'db865e840e17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default='0' backfills any existing rows; new rows are always set
    # explicitly by the application (question_service.py enumerates from 1).
    op.add_column('question_options', sa.Column('display_order', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_options', 'display_order')
    # ### end Alembic commands ###
