"""rename session states to ANSWERING GENERATING RESULTS

Revision ID: 4f95d907cb94
Revises: 789f8255619f
Create Date: 2026-05-26 20:13:02.183414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f95d907cb94'
down_revision: Union[str, None] = '789f8255619f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
