"""added swipe mechanic type to questions

Revision ID: 6ffaa2b2e586
Revises: db865e840e17
Create Date: 2026-05-29 23:27:41.781327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ffaa2b2e586'
down_revision: Union[str, None] = 'db865e840e17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
