"""remove swipe and update session states

Revision ID: 789f8255619f
Revises: fe0cadaed215
Create Date: 2026-05-26 19:44:55.363381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '789f8255619f'
down_revision: Union[str, None] = 'fe0cadaed215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('swipes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('swipes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('participant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('direction', postgresql.ENUM('YES', 'NO', name='swipedirection'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category_options.id'], name=op.f('swipes_category_id_fkey')),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], name=op.f('swipes_participant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('swipes_pkey')),
    sa.UniqueConstraint('participant_id', 'category_id', name=op.f('uq_swipe_participant_category'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
