"""add_cascade_deletes

Revision ID: db865e840e17
Revises: 669e9a429200
Create Date: 2026-05-26 22:51:33.094903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db865e840e17'
down_revision: Union[str, None] = '669e9a429200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('answers_question_id_fkey'), 'answers', type_='foreignkey')
    op.drop_constraint(op.f('answers_participant_id_fkey'), 'answers', type_='foreignkey')
    op.create_foreign_key(None, 'answers', 'participants', ['participant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'answers', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('participants_session_id_fkey'), 'participants', type_='foreignkey')
    op.create_foreign_key(None, 'participants', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('question_options_question_id_fkey'), 'question_options', type_='foreignkey')
    op.create_foreign_key(None, 'question_options', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('questions_session_id_fkey'), 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('results_session_id_fkey'), 'results', type_='foreignkey')
    op.create_foreign_key(None, 'results', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'sessions', 'participants', ['host_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.create_foreign_key(op.f('results_session_id_fkey'), 'results', 'sessions', ['session_id'], ['id'])
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key(op.f('questions_session_id_fkey'), 'questions', 'sessions', ['session_id'], ['id'])
    op.drop_constraint(None, 'question_options', type_='foreignkey')
    op.create_foreign_key(op.f('question_options_question_id_fkey'), 'question_options', 'questions', ['question_id'], ['id'])
    op.drop_constraint(None, 'participants', type_='foreignkey')
    op.create_foreign_key(op.f('participants_session_id_fkey'), 'participants', 'sessions', ['session_id'], ['id'])
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.create_foreign_key(op.f('answers_participant_id_fkey'), 'answers', 'participants', ['participant_id'], ['id'])
    op.create_foreign_key(op.f('answers_question_id_fkey'), 'answers', 'questions', ['question_id'], ['id'])
    # ### end Alembic commands ###
