"""add FK constraints and unique constraints

Revision ID: fe0cadaed215
Revises: ff5a82bea801
Create Date: 2026-05-25 19:37:23.041420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe0cadaed215'
down_revision: Union[str, None] = 'ff5a82bea801'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answers', 'answered_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.create_unique_constraint('uq_answer_participant_question', 'answers', ['participant_id', 'question_id'])
    op.alter_column('participants', 'joined_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('sessions', 'answered_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.create_foreign_key(None, 'sessions', 'participants', ['host_id'], ['id'], use_alter=True)
    op.create_unique_constraint('uq_swipe_participant_category', 'swipes', ['participant_id', 'category_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_swipe_participant_category', 'swipes', type_='unique')
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.alter_column('sessions', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('sessions', 'answered_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('participants', 'joined_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint('uq_answer_participant_question', 'answers', type_='unique')
    op.alter_column('answers', 'answered_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
